'use strict';
const crypto = require('node:crypto');

// Pure functions: database snapshot in, Asterisk configuration text out. Input has already been
// validated by strict whitelists (see schemas.js); the asserts below are a second line of defence so
// a bad row can never inject configuration.

const SAFE = /^[A-Za-z0-9 ._~+=@:/,!%^&*()?\[\]\p{L}\p{N}'-]*$/u;
const FORBIDDEN = /[\r\n;#${}"\\<>|]/;

function assertSafe(label, value) {
  const s = String(value ?? '');
  if (FORBIDDEN.test(s) || !SAFE.test(s)) throw new Error(`refusing to render unsafe ${label}`);
  return s;
}

const HANGUP_CAUSE = { busy: 17, congestion: 34, reject: 21 };

function endpointName(trunk) { return `trk-${trunk.name}`; }

function transportName(t) { return t === 'tcp' ? 'transport-tcp' : 'transport-udp'; }

function renderPjsip({ extensions, trunks }) {
  const out = ['; GENERATED by the backend from the database. Do not edit: changes are overwritten.', ''];

  out.push('; ------------------------------------------------------------------ extensions');
  for (const e of extensions) {
    if (!e.enabled) continue;
    const num = assertSafe('extension number', e.number);
    const name = assertSafe('display name', e.display_name).replace(/"/g, '');
    if (e.webrtc_enabled && e.secret) {
      out.push(
        `[${num}](ep-webrtc)`, `aors = ${num}`, `auth = ${num}-auth`, `callerid = "${name}" <${num}>`, '',
        `[${num}](aor-common)`, '',
        `[${num}-auth](auth-common)`, `username = ${num}`, `password = ${assertSafe('secret', e.secret)}`, '',
      );
    }
    if (e.phone_enabled && e.phone_secret) {
      out.push(
        `[${num}-phone](ep-phone)`, `aors = ${num}-phone`, `auth = ${num}-phone-auth`, `callerid = "${name}" <${num}>`, '',
        `[${num}-phone](aor-common)`, '',
        `[${num}-phone-auth](auth-common)`, `username = ${num}-phone`, `password = ${assertSafe('secret', e.phone_secret)}`, '',
      );
    }
  }

  out.push('; ----------------------------------------------------------------------- trunks');
  for (const t of trunks) {
    if (!t.enabled) continue;
    const ep = endpointName(t);
    const host = assertSafe('trunk host', t.host);
    const uri = `sip:${host}:${t.port}${t.transport === 'tcp' ? ';transport=tcp' : ''}`;
    const hasAuth = !!(t.username && t.password);

    out.push(
      `[${ep}](ep-trunk)`,
      `transport = ${transportName(t.transport)}`,
      `aors = ${ep}`,
      `context = from-trunk-${t.name}`,
      `allow = ${t.codecs.map((c) => assertSafe('codec', c)).join(',')}`,
      `dtmf_mode = ${assertSafe('dtmf mode', t.dtmf_mode)}`,
    );
    if (hasAuth) out.push(`outbound_auth = ${ep}-auth`);
    if (t.from_user) out.push(`from_user = ${assertSafe('from user', t.from_user)}`);
    if (t.from_domain) out.push(`from_domain = ${assertSafe('from domain', t.from_domain)}`);
    if (t.max_channels > 0) out.push(`device_state_busy_at = ${Number(t.max_channels)}`);
    out.push('');

    out.push(`[${ep}](aor-trunk)`, `contact = ${uri}`, `qualify_frequency = ${t.qualify ? 60 : 0}`, '');

    if (hasAuth) {
      out.push(
        `[${ep}-auth](auth-common)`,
        `username = ${assertSafe('auth username', t.auth_username || t.username)}`,
        `password = ${assertSafe('trunk password', t.password)}`,
        '',
      );
    }

    if (t.auth_mode === 'register') {
      const domain = t.from_domain || host;
      out.push(
        `[${ep}]`, 'type = registration',
        `transport = ${transportName(t.transport)}`,
        `outbound_auth = ${ep}-auth`,
        `server_uri = ${uri}`,
        `client_uri = sip:${assertSafe('username', t.username)}@${assertSafe('domain', domain)}`,
        `contact_user = ${assertSafe('username', t.username)}`,
        `expiration = ${Number(t.register_expiry)}`,
        'retry_interval = 60', 'forbidden_retry_interval = 600', 'max_retries = 10000', 'auth_rejection_permanent = no',
        'line = yes', `endpoint = ${ep}`, '',
      );
    }

    // Inbound calls are accepted from this trunk only when they arrive from one of its addresses.
    const matches = [...new Set([host, ...(t.match_ips || [])])];
    out.push(`[${ep}]`, 'type = identify', `endpoint = ${ep}`, ...matches.map((m) => `match = ${assertSafe('match address', m)}`), '');
  }
  return `${out.join('\n')}\n`;
}

/** What a destination does once a call has been routed to it. Always followed by a Hangup by the caller. */
function destinationLines(dest, indent = ' same => n,') {
  if (!dest) return [`${indent}Hangup(21)`];
  switch (dest.type) {
    case 'extension':
      return [`${indent}Gosub(sub-dial-ext,s,1(${assertSafe('extension', dest.value)}))`];
    case 'echo':
      return [`${indent}Goto(default,600,1)`];
    case 'hangup':
      return [`${indent}Hangup(${HANGUP_CAUSE[dest.value] || 21})`];
    default:
      throw new Error(`unknown destination type ${dest.type}`);
  }
}

function dialPattern(p) {
  assertSafe('dial pattern', p);
  if (p.startsWith('_')) return p;
  return /^[0-9*#+]+$/.test(p) ? p : `_${p}`;
}

function didPattern(did) {
  return did === '*' ? '_.' : assertSafe('did', did);
}

function renderDialplan({ extensions, groups, trunks, inbound, outbound }) {
  const out = ['; GENERATED by the backend from the database. Do not edit: changes are overwritten.', ''];
  const enabledExt = extensions.filter((e) => e.enabled);
  const enabledNumbers = new Set(enabledExt.map((e) => e.number));
  const enabledTrunks = trunks.filter((t) => t.enabled);
  const trunkById = new Map(enabledTrunks.map((t) => [Number(t.id), t]));

  // ------------------------------------------------------------- paging groups
  out.push('[page-members]');
  for (const g of groups) {
    if (!g.enabled) continue;
    const members = g.members.filter((m) => enabledNumbers.has(m));
    out.push(`exten => ${assertSafe('group number', g.number)},1,Set(MEMBERS=${members.join('-')})`, ' same => n,Return()');
  }
  out.push('');

  // -------------------------------------- per-extension outbound permission/caller id
  out.push('; An extension may place outbound calls only if it appears here.', '[ext-outbound]');
  for (const e of enabledExt) {
    if (!e.allow_outbound) continue;
    out.push(`exten => ${e.number},1,Set(OB_CID=${e.outbound_cid ? assertSafe('caller id', e.outbound_cid) : ''})`, ' same => n,Return()');
  }
  out.push('');

  out.push('; Caller id presented by each trunk when neither the route nor the extension sets one.', '[trunk-meta]');
  for (const t of enabledTrunks) {
    out.push(
      `exten => ${endpointName(t)},1,Set(TRUNK_CID=${t.caller_id_num ? assertSafe('caller id', t.caller_id_num) : ''})`,
      ` same => n,Set(TRUNK_CIDNAME=${t.caller_id_name ? assertSafe('caller id name', t.caller_id_name) : ''})`,
      ' same => n,Return()',
    );
  }
  out.push('');

  // ------------------------------------------------------------------ internal
  out.push('[default]');
  for (const e of enabledExt) {
    out.push(`exten => ${e.number},1,Gosub(sub-dial-ext,s,1(${e.number}))`, ' same => n,Hangup()');
  }
  for (const g of groups) {
    if (!g.enabled) continue;
    out.push(`exten => ${g.number},1,Gosub(sub-page,s,1(${g.number}))`, ' same => n,Hangup()');
  }
  // Outbound routes: one context per route, included in the order set by the administrator. Asterisk searches
  // included contexts in order and uses the first one with a matching pattern, so "order" really is the
  // priority, even for identical patterns. The extensions above always win over an outbound pattern.
  const routes = outbound
    .filter((r) => r.enabled)
    .map((r) => ({ r, trunkList: r.trunks.map((t) => trunkById.get(t.id)).filter(Boolean).map(endpointName) }))
    .filter((x) => x.trunkList.length)
    .sort((a, b) => a.r.position - b.r.position || a.r.id - b.r.id);
  for (const { r } of routes) out.push(`include => outrt-${Number(r.id)}`);
  out.push('');
  for (const { r, trunkList } of routes) {
    out.push(`[outrt-${Number(r.id)}]`, `; outbound route "${assertSafe('route name', r.name).replace(/[;]/g, '')}"`);
    r.patterns.forEach((p, i) => {
      out.push(
        `exten => ${dialPattern(p)},1,NoOp(Outbound route ${r.id} pattern ${i + 1})`,
        ` same => n,Gosub(sub-outbound,s,1(${Number(r.id)},${assertSafe('prepend', r.prepend)}\${EXTEN:${Number(r.strip)}},${trunkList.join('&')},${r.cid_num ? assertSafe('caller id', r.cid_num) : ''},${r.emergency ? 1 : 0}))`,
        ' same => n,Hangup()',
      );
    });
    out.push('');
  }

  // -------------------------------------------------------------- from trunks
  for (const t of enabledTrunks) {
    out.push(`[from-trunk-${t.name}]`);
    const routes = inbound.filter((r) => r.enabled && (r.trunk_id === null || r.trunk_id === Number(t.id)));
    // A route bound to this trunk beats a route for every trunk with the same number.
    const byDid = new Map();
    for (const r of routes) {
      const existing = byDid.get(r.did);
      if (!existing || (existing.trunk_id === null && r.trunk_id !== null)) byDid.set(r.did, r);
    }
    for (const r of byDid.values()) {
      out.push(
        `; inbound route "${assertSafe('route name', r.name)}"`,
        `exten => ${didPattern(r.did)},1,NoOp(Inbound ${t.name} -> route ${r.id})`,
        ' same => n,Set(CDR(userfield)=in:${EXTEN})',
      );
      if (r.cid_name_prefix) out.push(` same => n,Set(CALLERID(name)=${assertSafe('prefix', r.cid_name_prefix)} \${CALLERID(name)})`);
      out.push(...destinationLines(r.destination), ' same => n,Hangup()');
    }
    if (!byDid.has('*')) {
      out.push(
        '; unmatched inbound calls',
        'exten => _.,1,NoOp(Inbound call on ${EXTEN} from ${CALLERID(num)} matched no route)',
        ' same => n,Set(CDR(userfield)=in:${EXTEN}:unrouted)',
      );
      out.push(...destinationLines(t.inbound_default), ' same => n,Hangup(1)');
    }
    out.push('');
  }
  if (!enabledTrunks.length) out.push('; no trunks configured', '');

  return `${out.join('\n')}\n`;
}

function renderAll(snapshot) {
  const pjsip = renderPjsip(snapshot);
  const dialplan = renderDialplan(snapshot);
  const checksum = crypto.createHash('sha256').update(pjsip).update('\0').update(dialplan).digest('hex');
  return { pjsip, dialplan, checksum };
}

module.exports = { renderPjsip, renderDialplan, renderAll, endpointName };
