'use strict';
const crypto = require('node:crypto');
const { dstContext } = require('./destinations');

// Pure functions: database snapshot in, Asterisk configuration text out. Input has already been
// validated by strict whitelists (see schemas.js); the asserts below are a second line of defence so
// a bad row can never inject configuration.

const SAFE = /^[A-Za-z0-9 ._~+=@:/,!%^&*()?\[\]\p{L}\p{N}'-]*$/u;
const FORBIDDEN = /[\r\n;#${}"\\<>|]/;

function assertSafe(label, value) {
  const s = String(value ?? '');
  if (FORBIDDEN.test(s) || !SAFE.test(s)) throw new Error(`refusing to render unsafe ${label}`);
  return s;
}

// Prompts live in a volume mounted at the same place in the backend (writes) and Asterisk (reads).
const PROMPT_DIR = '/pbx-media/prompts';
const VOICEMAIL_DIR = '/pbx-media/voicemail';

const HANGUP_CAUSE = { busy: 17, congestion: 34, reject: 21 };

/** A menu key is exactly one of 0-9, * or #. (# is not allowed by assertSafe in general, but is a normal key here.) */
function menuKey(k) {
  if (!/^[0-9*#]$/.test(String(k))) throw new Error('refusing to render unsafe menu key');
  return k;
}
function endpointName(trunk) { return `trk-${trunk.name}`; }

function transportName(t) { return t === 'tcp' ? 'transport-tcp' : 'transport-udp'; }

function renderPjsip({ extensions, trunks }) {
  const out = ['; GENERATED by the backend from the database. Do not edit: changes are overwritten.', ''];

  out.push('; ------------------------------------------------------------------ extensions');
  for (const e of extensions) {
    if (!e.enabled) continue;
    const num = assertSafe('extension number', e.number);
    const name = assertSafe('display name', e.display_name).replace(/"/g, '');
    if (e.webrtc_enabled && e.secret) {
      out.push(
        `[${num}](ep-webrtc)`, `aors = ${num}`, `auth = ${num}-auth`, `callerid = "${name}" <${num}>`, '',
        `[${num}](aor-common)`, '',
        `[${num}-auth](auth-common)`, `username = ${num}`, `password = ${assertSafe('secret', e.secret)}`, '',
      );
    }
    if (e.phone_enabled && e.phone_secret) {
      out.push(
        `[${num}-phone](ep-phone)`, `aors = ${num}-phone`, `auth = ${num}-phone-auth`, `callerid = "${name}" <${num}>`, '',
        `[${num}-phone](aor-common)`, '',
        `[${num}-phone-auth](auth-common)`, `username = ${num}-phone`, `password = ${assertSafe('secret', e.phone_secret)}`, '',
      );
    }
  }

  out.push('; ----------------------------------------------------------------------- trunks');
  for (const t of trunks) {
    if (!t.enabled) continue;
    const ep = endpointName(t);
    const host = assertSafe('trunk host', t.host);
    const uri = `sip:${host}:${t.port}${t.transport === 'tcp' ? ';transport=tcp' : ''}`;
    const hasAuth = !!(t.username && t.password);

    out.push(
      `[${ep}](ep-trunk)`,
      `transport = ${transportName(t.transport)}`,
      `aors = ${ep}`,
      `context = from-trunk-${t.name}`,
      `allow = ${t.codecs.map((c) => assertSafe('codec', c)).join(',')}`,
      `dtmf_mode = ${assertSafe('dtmf mode', t.dtmf_mode)}`,
    );
    if (hasAuth) out.push(`outbound_auth = ${ep}-auth`);
    if (t.from_user) out.push(`from_user = ${assertSafe('from user', t.from_user)}`);
    if (t.from_domain) out.push(`from_domain = ${assertSafe('from domain', t.from_domain)}`);
    if (t.max_channels > 0) out.push(`device_state_busy_at = ${Number(t.max_channels)}`);
    out.push('');

    out.push(`[${ep}](aor-trunk)`, `contact = ${uri}`, `qualify_frequency = ${t.qualify ? 60 : 0}`, '');

    if (hasAuth) {
      out.push(
        `[${ep}-auth](auth-common)`,
        `username = ${assertSafe('auth username', t.auth_username || t.username)}`,
        `password = ${assertSafe('trunk password', t.password)}`,
        '',
      );
    }

    if (t.auth_mode === 'register') {
      const domain = t.from_domain || host;
      out.push(
        `[${ep}]`, 'type = registration',
        `transport = ${transportName(t.transport)}`,
        `outbound_auth = ${ep}-auth`,
        `server_uri = ${uri}`,
        `client_uri = sip:${assertSafe('username', t.username)}@${assertSafe('domain', domain)}`,
        `contact_user = ${assertSafe('username', t.username)}`,
        `expiration = ${Number(t.register_expiry)}`,
        'retry_interval = 60', 'forbidden_retry_interval = 600', 'max_retries = 10000', 'auth_rejection_permanent = no',
        'line = yes', `endpoint = ${ep}`, '',
      );
    }

    // Inbound calls are accepted from this trunk only when they arrive from one of its addresses.
    const matches = [...new Set([host, ...(t.match_ips || [])])];
    out.push(`[${ep}]`, 'type = identify', `endpoint = ${ep}`, ...matches.map((m) => `match = ${assertSafe('match address', m)}`), '');
  }
  return `${out.join('\n')}\n`;
}

/** Send the call to a destination's own context (rendered below). */
function destinationLines(dest, indent = ' same => n,') {
  if (dest && dest.type) {
    assertSafe('destination type', dest.type);
    assertSafe('destination value', dest.value);
  }
  return [`${indent}Goto(${dstContext(dest)},s,1)`];
}

function dialPattern(p) {
  assertSafe('dial pattern', p);
  if (p.startsWith('_')) return p;
  return /^[0-9*#+]+$/.test(p) ? p : `_${p}`;
}

function didPattern(did) {
  return assertSafe('did', did);
}

const MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];

/**
 * One dialplan context per destination ("dst-<type>-<value>", entered with Goto at s,1). Each starts with a hop
 * counter so a misconfigured loop (time condition -> time condition -> ...) is cut off instead of spinning.
 */
function renderDestinations({ extensions, ringGroups, timeConditions, announcements = [], ivrs = [], queues = [], conferences = [] }) {
  const out = ['; ------------------------------------------------------------------ destinations'];
  const hop = ' same => n,Gosub(sub-hop,s,1)';
  const ctx = (name, ...lines) => { out.push(`[${name}]`, 'exten => s,1,NoOp(' + name + ')', hop, ...lines, ''); };
  const goto = (dest, indent = ' same => n,') => destinationLines(dest, indent)[0];

  ctx('dst-echo-0', ' same => n,Goto(default,600,1)');
  ctx('dst-hangup-reject', ' same => n,Hangup(21)');
  ctx('dst-hangup-busy', ' same => n,Busy(10)', ' same => n,Hangup(17)');
  ctx('dst-hangup-congestion', ' same => n,Congestion(10)', ' same => n,Hangup(34)');

  for (const e of extensions) {
    ctx(`dst-extension-${assertSafe('extension', e.number)}`, ` same => n,Gosub(sub-dial-ext,s,1(${e.number}))`, ' same => n,Hangup()');
  }

  // A voicemail box is a destination of its own (dst-voicemail-<ext>): sub-dial-ext sends unanswered / busy / unreachable
  // calls there, and routes, menus and forwarding can name it. The caller hears the greeting (if any) and a beep, then the
  // message is recorded to the shared media volume. The file is reported to the backend with a UserEvent: once the caller
  // finishes, or from the "h" extension when the caller simply hangs up (Record keeps the file on hangup, option "k"; "q" because no beep sound file is installed, the tone above is the beep).
  for (const e of extensions) {
    const num = assertSafe('extension', e.number);
    const name = `dst-voicemail-${num}`;
    if (!e.enabled || !e.voicemail_enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    const greeting = e.voicemail_greeting_id ? [` same => n,Playback(${PROMPT_DIR}/${Number(e.voicemail_greeting_id)})`] : [];
    const report = `UserEvent(VoicemailLeft,Extension: ${num},File: \${VM_FILE},Caller: \${VM_CALLER})`;
    out.push(
      `[${name}]`, `exten => s,1,NoOp(${name})`, hop,
      ' same => n,Answer()',
      ' same => n,Wait(1)',
      ` same => n,Set(VM_FILE=${num}-\${UNIQUEID}.wav)`,
      // The caller id is chosen by whoever is calling, so only plain characters are passed on in the event.
      ' same => n,Set(VM_CALLER=${FILTER(0-9A-Za-z+*#._@,${CALLERID(num)})})',
      ' same => n,Set(VM_STARTED=0)',
      ...greeting,
      ' same => n,Playtones(!1000/350)',
      ' same => n,Wait(0.6)',
      ' same => n,StopPlayTones()',
      ' same => n,Set(VM_STARTED=1)',
      ` same => n,Record(${VOICEMAIL_DIR}/\${VM_FILE},4,${Number(e.voicemail_max_secs) || 120},kq)`,
      ' same => n,Set(VM_DONE=1)',
      ` same => n,${report}`,
      ' same => n,Hangup()',
      `exten => h,1,ExecIf($["\${VM_STARTED}" = "1" & "\${VM_DONE}" != "1"]?${report})`,
      '');
  }

  const rgNumbers = new Set(ringGroups.map((g) => g.number));
  const known = new Set(extensions.filter((e) => e.enabled).map((e) => e.number));
  for (const g of ringGroups) {
    const name = `dst-ringgroup-${assertSafe('ring group', g.number)}`;
    if (!g.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    const members = g.members.filter((m) => known.has(m));
    const secs = Number(g.ring_secs) || 20;
    const lines = [];
    if (g.strategy === 'sequential') {
      members.forEach((m, i) => {
        lines.push(
          ` same => n,Gosub(sub-dialstr,s,1(${assertSafe('member', m)},1))`,
          ` same => n,GotoIf($["\${DIALSTR}" = ""]?m${i}next)`,
          ` same => n,Dial(\${DIALSTR},${secs},U(sub-rec-callee))`,
          ' same => n,GotoIf($["\${DIALSTATUS}" = "ANSWER" | "\${DIALSTATUS}" = "CANCEL"]?done)',
          ` same => n(m${i}next),NoOp(member ${i} did not answer)`,
        );
      });
    } else {
      lines.push(' same => n,Set(RG_TARGETS=)');
      for (const m of members) lines.push(` same => n,Gosub(sub-rg-add,s,1(${assertSafe('member', m)}))`);
      lines.push(
        ' same => n,GotoIf($["\${RG_TARGETS}" = ""]?fail)',
        ` same => n,Dial(\${RG_TARGETS},${secs},U(sub-rec-callee))`,
        ' same => n,GotoIf($["\${DIALSTATUS}" = "ANSWER" | "\${DIALSTATUS}" = "CANCEL"]?done)',
      );
    }
    lines.push(' same => n(fail),NoOp(ring group fallback)');
    lines.push(g.fail_dest ? goto(g.fail_dest) : ' same => n,Hangup(19)');
    lines.push(' same => n(done),Hangup()');
    ctx(name, ...lines);
  }
  void rgNumbers;

  for (const t of timeConditions) {
    const name = `dst-timecondition-${Number(t.id)}`;
    if (!t.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    const tz = assertSafe('time zone', t.timezone);
    const lines = [];
    if (t.override === 'open') lines.push(goto(t.match_dest));
    else if (t.override === 'closed') lines.push(goto(t.nomatch_dest));
    else {
      for (const h of t.holidays) {
        lines.push(` same => n,GotoIfTime(*,*,${Number(h.day)},${MONTHS[Number(h.month) - 1]},${tz}?closed)`);
      }
      for (const r of t.rules) {
        for (const d of r.days) {
          lines.push(` same => n,GotoIfTime(${assertSafe('time', r.from)}-${assertSafe('time', r.to)},${assertSafe('day', d)},*,*,${tz}?open)`);
        }
      }
      lines.push(goto(t.nomatch_dest));
      lines.push(` same => n(open),NoOp(open)`, goto(t.match_dest), ' same => n,Hangup()');
      lines.push(` same => n(closed),NoOp(closed)`, goto(t.nomatch_dest));
    }
    ctx(name, ...lines);
  }

  for (const a of announcements) {
    const name = `dst-announcement-${Number(a.id)}`;
    if (!a.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    ctx(name,
      ' same => n,Answer()',
      ` same => n,Playback(${PROMPT_DIR}/${Number(a.prompt_id)})`,
      a.next_dest ? goto(a.next_dest) : ' same => n,Hangup()',
      ' same => n,Hangup()');
  }

  for (const q of queues) {
    const name = `dst-queue-${assertSafe('queue', q.number)}`;
    if (!q.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    ctx(name,
      ` same => n,Queue(${queueName(q)},r,,,${Number(q.max_wait_secs)})`,
      ' same => n,GotoIf($["\${QUEUESTATUS}" = "TIMEOUT" | "\${QUEUESTATUS}" = "FULL" | "\${QUEUESTATUS}" = "JOINEMPTY" | "\${QUEUESTATUS}" = "LEAVEEMPTY" | "\${QUEUESTATUS}" = "JOINUNAVAIL" | "\${QUEUESTATUS}" = "LEAVEUNAVAIL"]?fail)',
      ' same => n,Hangup()',
      ` same => n(fail),UserEvent(QueueFailed,Queue: ${q.number},Status: \${QUEUESTATUS},Caller: \${CALLERID(num)},Uniqueid: \${UNIQUEID})`,
      q.fail_dest ? goto(q.fail_dest) : ' same => n,Hangup(34)');
  }

  // Conference rooms. Options come from the database and are applied per call with CONFBRIDGE(); the profiles they
  // start from are static (confbridge.conf). A PIN is asked for with a short tone (no sound files are installed) and
  // compared here: the room PIN lets you in, the administrator PIN lets you in with the right to kick, lock and mute others.
  for (const c of conferences) {
    const num = assertSafe('conference', c.number);
    const name = `dst-conference-${num}`;
    if (!c.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    const pin = (v, what) => {
      if (v === null || v === undefined || v === '') return null;
      if (!/^[0-9]{3,10}$/.test(String(v))) throw new Error(`refusing to render unsafe ${what}`);
      return String(v);
    };
    const roomPin = pin(c.pin, 'conference PIN');
    const adminPin = pin(c.admin_pin, 'conference administrator PIN');
    // A profile set with CONFBRIDGE() is used by ConfBridge(<room>) only when no profile is named in the call.
    const lines = [
      ' same => n,Answer()',
      ' same => n,Set(CONFBRIDGE(bridge,template)=c-bridge)',
      ' same => n,Set(CONFBRIDGE(user,template)=c-user)',
      ' same => n,Set(CONFBRIDGE(menu,template)=c-menu)',
    ];
    if (Number(c.max_members) > 0) lines.push(` same => n,Set(CONFBRIDGE(bridge,max_members)=${Number(c.max_members)})`);
    if (c.mute_on_join) lines.push(' same => n,Set(CONFBRIDGE(user,startmuted)=yes)');
    if (roomPin || adminPin) {
      lines.push(
        ' same => n,Set(CF_TRIES=0)',
        ' same => n(ask),Set(CF_TRIES=$[${CF_TRIES} + 1])',
        ' same => n,Playtones(!800/250)',
        ' same => n,Wait(0.4)',
        ' same => n,StopPlayTones()',
        ' same => n,Read(CF_PIN,,10,,1,10)',
      );
      if (adminPin) lines.push(` same => n,GotoIf($["\${CF_PIN}" = "${adminPin}"]?admin)`);
      if (roomPin) lines.push(` same => n,GotoIf($["\${CF_PIN}" = "${roomPin}"]?join)`);
      else lines.push(' same => n,GotoIf($["${CF_PIN}" = ""]?join)');
      lines.push(
        ' same => n,Playtones(congestion)',
        ' same => n,Wait(1.5)',
        ' same => n,StopPlayTones()',
        ' same => n,GotoIf($[${CF_TRIES} < 3]?ask)',
        ' same => n,Hangup(21)',
      );
      if (adminPin) lines.push(' same => n(admin),Set(CONFBRIDGE(user,admin)=yes)');
    }
    lines.push(` same => n(join),ConfBridge(${num})`, ' same => n,Hangup()');
    ctx(name, ...lines);
  }

  const extNumbers = extensions.filter((e) => e.enabled).map((e) => e.number);
  for (const i of ivrs) {
    const name = `dst-ivr-${assertSafe('menu', i.number)}`;
    if (!i.enabled) { ctx(name, ' same => n,Hangup(21)'); continue; }
    const timeout = Number(i.timeout_secs) || 6;
    const repeats = Number(i.max_repeats) || 2;
    out.push(`[${name}]`, `exten => s,1,NoOp(${name})`, hop,
      ' same => n,Answer()',
      ' same => n,Set(IVR_TRIES=0)',
      ' same => n(menu),Set(TIMEOUT(digit)=3)',
      ` same => n,Set(TIMEOUT(response)=${timeout})`);
    if (i.prompt_id) out.push(` same => n,Background(${PROMPT_DIR}/${Number(i.prompt_id)})`);
    out.push(` same => n,WaitExten(${timeout})`);
    for (const o of i.options) {
      out.push(`exten => ${menuKey(o.digit)},1,NoOp(Menu ${i.number}: key ${o.digit})`, goto(o.dest));
    }
    if (i.allow_extension_dial) {
      for (const n of extNumbers) {
        if (i.options.some((o) => o.digit === n)) continue;
        out.push(`exten => ${n},1,NoOp(Menu ${i.number}: direct dial ${n})`, goto({ type: 'extension', value: n }));
      }
    }
    out.push(
      'exten => t,1,Set(IVR_TRIES=$[0${IVR_TRIES} + 1])',
      ` same => n,GotoIf($[\${IVR_TRIES} >= ${repeats}]?giveup)`,
      ' same => n,Goto(s,menu)',
      ' same => n(giveup),NoOp(menu gave up)',
      i.fail_dest ? goto(i.fail_dest) : ' same => n,Hangup(16)',
      'exten => i,1,Goto(t,1)',
      'exten => h,1,NoOp(caller left the menu)',
      '');
  }
  return out;
}

function renderDialplan({ extensions, groups, trunks, inbound, outbound, ringGroups = [], timeConditions = [], announcements = [], ivrs = [], queues = [], conferences = [] }) {
  const out = ['; GENERATED by the backend from the database. Do not edit: changes are overwritten.', ''];
  const enabledExt = extensions.filter((e) => e.enabled);
  const enabledNumbers = new Set(enabledExt.map((e) => e.number));
  const enabledTrunks = trunks.filter((t) => t.enabled);
  const trunkById = new Map(enabledTrunks.map((t) => [Number(t.id), t]));

  // ------------------------------------------------------------- paging groups
  out.push('[page-members]');
  for (const g of groups) {
    if (!g.enabled) continue;
    const members = g.members.filter((m) => enabledNumbers.has(m));
    out.push(`exten => ${assertSafe('group number', g.number)},1,Set(MEMBERS=${members.join('-')})`, ' same => n,Return()');
  }
  out.push('');

  // -------------------------------------- per-extension outbound permission/caller id
  out.push('; An extension may place outbound calls only if it appears here.', '[ext-outbound]');
  for (const e of enabledExt) {
    if (!e.allow_outbound) continue;
    out.push(`exten => ${e.number},1,Set(OB_CID=${e.outbound_cid ? assertSafe('caller id', e.outbound_cid) : ''})`, ' same => n,Return()');
  }
  out.push('');

  out.push('; Device state of each extension (browser + phone together). Queue members and presence lamps watch these.', '[ext-hints]');
  for (const e of enabledExt) {
    out.push(`exten => ${assertSafe('extension', e.number)},hint,PJSIP/${e.number}&PJSIP/${e.number}-phone`);
  }
  out.push('');

  // Do-not-disturb and forwarding, read by sub-dial-ext / sub-dialstr. Values are dialplan context names.
  out.push('; Per-extension call handling (do not disturb, forwarding).', '[ext-settings]');
  for (const e of enabledExt) {
    const ctx = (d) => (d ? assertSafe('forward destination', dstContext(d)) : '');
    out.push(
      `exten => ${e.number},1,Set(X_DND=${e.dnd ? 1 : 0})`,
      ` same => n,Set(X_FWD_ALL=${ctx(e.fwd_all)})`,
      ` same => n,Set(X_FWD_BUSY=${ctx(e.fwd_busy)})`,
      ` same => n,Set(X_FWD_NA=${ctx(e.fwd_noanswer)})`,
      ` same => n,Set(X_NA_SECS=${Number(e.noanswer_secs) || 25})`,
      ` same => n,Set(X_VM=${e.voicemail_enabled ? 1 : 0})`,
      ' same => n,Return()',
    );
  }
  out.push('');

  // Extensions whose calls are recorded: sub-rec-caller / sub-rec-callee only check that the extension exists here.
  out.push('; Extensions with call recording switched on.', '[ext-record]');
  for (const e of enabledExt) {
    if (e.record_calls) out.push(`exten => ${assertSafe('extension', e.number)},1,Return()`);
  }
  out.push('');

  out.push('; Caller id presented by each trunk when neither the route nor the extension sets one.', '[trunk-meta]');
  for (const t of enabledTrunks) {
    out.push(
      `exten => ${endpointName(t)},1,Set(TRUNK_CID=${t.caller_id_num ? assertSafe('caller id', t.caller_id_num) : ''})`,
      ` same => n,Set(TRUNK_CIDNAME=${t.caller_id_name ? assertSafe('caller id name', t.caller_id_name) : ''})`,
      ` same => n,Set(TRUNK_REC=${t.record_calls ? 1 : 0})`,
      ' same => n,Return()',
    );
  }
  out.push('');

  // ------------------------------------------------------------------ internal
  out.push('[default]');
  for (const e of enabledExt) {
    // userfield remembers what the caller dialled: a Goto into a destination context changes the CDR destination to "s".
    out.push(`exten => ${e.number},1,Set(CDR(userfield)=to:\${EXTEN})`, ` same => n,Gosub(sub-dial-ext,s,1(${e.number}))`, ' same => n,Hangup()');
  }
  for (const g of groups) {
    if (!g.enabled) continue;
    out.push(`exten => ${g.number},1,Gosub(sub-page,s,1(${g.number}))`, ' same => n,Hangup()');
  }
  for (const g of ringGroups) {
    if (!g.enabled) continue;
    out.push(`exten => ${assertSafe('ring group number', g.number)},1,Set(CDR(userfield)=to:\${EXTEN})`, ` same => n,Goto(dst-ringgroup-${g.number},s,1)`);
  }
  for (const i of ivrs) {
    if (!i.enabled) continue;
    out.push(`exten => ${assertSafe('menu number', i.number)},1,Set(CDR(userfield)=to:\${EXTEN})`, ` same => n,Goto(dst-ivr-${i.number},s,1)`);
  }
  for (const q of queues) {
    if (!q.enabled) continue;
    out.push(`exten => ${assertSafe('queue number', q.number)},1,Set(CDR(userfield)=to:\${EXTEN})`, ` same => n,Goto(dst-queue-${q.number},s,1)`);
  }
  for (const c of conferences) {
    if (!c.enabled) continue;
    out.push(`exten => ${assertSafe('conference number', c.number)},1,Set(CDR(userfield)=to:\${EXTEN})`, ` same => n,Goto(dst-conference-${c.number},s,1)`);
  }
  // Outbound routes: one context per route, included in the order set by the administrator. Asterisk searches
  // included contexts in order and uses the first one with a matching pattern, so "order" really is the
  // priority, even for identical patterns. The extensions above always win over an outbound pattern.
  const routes = outbound
    .filter((r) => r.enabled)
    .map((r) => ({ r, trunkList: r.trunks.map((t) => trunkById.get(t.id)).filter(Boolean).map(endpointName) }))
    .filter((x) => x.trunkList.length)
    .sort((a, b) => a.r.position - b.r.position || a.r.id - b.r.id);
  for (const { r } of routes) out.push(`include => outrt-${Number(r.id)}`);
  out.push('');
  for (const { r, trunkList } of routes) {
    out.push(`[outrt-${Number(r.id)}]`, `; outbound route "${assertSafe('route name', r.name).replace(/[;]/g, '')}"`);
    r.patterns.forEach((p, i) => {
      out.push(
        `exten => ${dialPattern(p)},1,NoOp(Outbound route ${r.id} pattern ${i + 1})`,
        ` same => n,Gosub(sub-outbound,s,1(${Number(r.id)},${assertSafe('prepend', r.prepend)}\${EXTEN:${Number(r.strip)}},${trunkList.join('&')},${r.cid_num ? assertSafe('caller id', r.cid_num) : ''},${r.emergency ? 1 : 0}))`,
        ' same => n,Hangup()',
      );
    });
    out.push('');
  }

  // -------------------------------------------------------------- from trunks
  for (const t of enabledTrunks) {
    out.push(`[from-trunk-${t.name}]`);
    const routes = inbound.filter((r) => r.enabled && (r.trunk_id === null || r.trunk_id === Number(t.id)));
    // A route bound to this trunk beats a route for every trunk with the same number.
    const byDid = new Map();
    for (const r of routes) {
      const existing = byDid.get(r.did);
      if (!existing || (existing.trunk_id === null && r.trunk_id !== null)) byDid.set(r.did, r);
    }
    // "*" (any number) is two patterns: numbers that start with a digit, and numbers that start with "+".
    const patterns = (did) => (did === '*' ? ['_X.', '_+X.'] : [didPattern(did)]);
    for (const r of byDid.values()) {
      out.push(`; inbound route "${assertSafe('route name', r.name)}"`);
      for (const pattern of patterns(r.did)) {
        out.push(`exten => ${pattern},1,NoOp(Inbound ${t.name} -> route ${r.id})`, ' same => n,Set(CDR(userfield)=in:${EXTEN})');
        if (t.record_calls) out.push(' same => n,Gosub(sub-rec-start,s,1)');
        if (r.cid_name_prefix) out.push(` same => n,Set(CALLERID(name)=${assertSafe('prefix', r.cid_name_prefix)} \${CALLERID(name)})`);
        out.push(...destinationLines(r.destination), ' same => n,Hangup()');
      }
    }
    if (!byDid.has('*')) {
      out.push('; unmatched inbound calls');
      for (const pattern of patterns('*')) {
        out.push(
          `exten => ${pattern},1,NoOp(Inbound call on \${EXTEN} from \${CALLERID(num)} matched no route)`,
          ' same => n,Set(CDR(userfield)=in:${EXTEN}:unrouted)',
          ...(t.record_calls ? [' same => n,Gosub(sub-rec-start,s,1)'] : []),
          ...destinationLines(t.inbound_default),
          ' same => n,Hangup(1)',
        );
      }
    }
    out.push('');
  }
  if (!enabledTrunks.length) out.push('; no trunks configured', '');

  out.push(...renderDestinations({ extensions, ringGroups, timeConditions, announcements, ivrs, queues, conferences }));

  return `${out.join('\n')}\n`;
}

const queueName = (q) => `q-${assertSafe('queue number', q.number)}`;

/** queues_generated.conf: one section per queue, members are Local channels that ring the extension's devices. */
function renderQueues({ queues = [], extensions }) {
  const out = ['; GENERATED by the backend from the database. Do not edit: changes are overwritten.', ''];
  const known = new Set(extensions.filter((e) => e.enabled).map((e) => e.number));
  for (const q of queues) {
    if (!q.enabled) continue;
    const empty = q.hold_when_empty ? [] : ['joinempty = unavailable,invalid,paused', 'leavewhenempty = unavailable,invalid,paused'];
    out.push(
      `[${queueName(q)}]`,
      `strategy = ${assertSafe('strategy', q.strategy)}`,
      `timeout = ${Number(q.member_timeout)}`,
      'retry = 3',
      `wrapuptime = ${Number(q.wrapup_secs)}`,
      `maxlen = ${Number(q.max_callers)}`,
      'ringinuse = no',
      'autopause = no',
      'announce-holdtime = no',
      'announce-position = no',
      'reportholdtime = no',
      ...empty,
    );
    for (const m of q.members.filter((n) => known.has(n))) {
      out.push(`member => Local/${assertSafe('member', m)}@queue-member/n,0,E${m},hint:${m}@ext-hints`);
    }
    out.push('');
  }
  return `${out.join('\n')}\n`;
}

function renderAll(snapshot) {
  const pjsip = renderPjsip(snapshot);
  const dialplan = renderDialplan(snapshot);
  const queues = renderQueues(snapshot);
  const sha = (...parts) => { const h = crypto.createHash('sha256'); for (const p of parts) h.update(p).update('\0'); return h.digest('hex'); };
  return { pjsip, dialplan, queues, checksum: sha(pjsip, dialplan, queues), pjsipChecksum: sha(pjsip), dialplanChecksum: sha(dialplan), queuesChecksum: sha(queues) };
}

/** The agent order of each queue as last loaded: only the in-order (linear) strategy depends on it. */
function queueOrders({ queues = [], extensions }) {
  const known = new Set(extensions.filter((e) => e.enabled).map((e) => e.number));
  return new Map(queues.filter((q) => q.enabled).map((q) => [q.number, q.members.filter((m) => known.has(m)).join(',')]));
}

module.exports = { renderPjsip, renderDialplan, renderQueues, renderAll, queueOrders, endpointName };
